workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "GameON-Modularization.xcworkspace" # Workspace name
          XCODE_SCHEME: "GameON" # Scheme you want to build (should be your app's scheme)
    scripts:
      - name: Run tests
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \  # Use workspace instead of project
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" \  # Use workspace instead of project
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - atharianrahmadani@gmail.com # Email for build notifications
