workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameON.xcodeproj"
          XCODE_WORKSPACE: "./GameON/GameON-Modularization.xcworkspace"
          XCODE_SCHEME: "GameON"  # or any other valid scheme you want to use
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - atharianrahmadani@gmail.com
    trigger:
      events:
        - push
      branch_patterns:
        - pattern: "master"
          include: true
